### ISSUE TITLE
i'm in the need for speed

### ISSUE THREAD

**Issue by lmcneil7** [lmcneil7/teen-titans#56]
### ***WELCOME BACK***

Since we decided that we would do another semester of teen titans, I knew it would be a project that I worked on at random periods of time. Here's a random period of time! It's been a while, but Shannon and I were reminiscing about Digital Humanities, and I got the motivation to start another project. This project will be focusing on fixing and finishing the tasks that I didn't get a chance to do by the end of the Spring Semester of 2020.

@smdunn921 @amberpeddicord I'm going to be making many issues, but many of them will focus on the stuff that I want to do. However, this is *OUR* project, and I would love to hear if you guys got anything you want to do. Feel free to add to the issues, make your own, or add to the new project **"rise of the teen titans"**. 

As usual, I work better with lists, so I'm going to make an overarching to-do list. I'll issue the more specific tasks as I go along, but this is more of an issue to keep track of my main goals for **rise of the teen titans**. It's also going to be an issue that I frequently update whenever I have information or add.

- ***Original Date:*** 02 March 2021
- ***Last Updated Date:*** 02 March 2021

**To-Do:**
- [ ] Learn how to make CBML and mark-up _The New Teen Titans: The Judas Contract_ (It's the comic that the second season is based on)
***For context: I originally wanted to do this for our spring semester project, but I ended up running out of time. I still talked about the comic in the Analysis, but I want to incorporate it into our site's comics. Also, hopefully, if it goes well, try it on the other comic mark-up I did.***
- [ ] Fix the map
***For context: I'm actually pretty proud of the map overall; it doesn't show what I need it to, though. It looked fine before I tried adding the animation. I want it to show the individual titans' movement, but it didn't work out the way I wanted it. I need to mess around with it.***
- [ ] Find another way to make the video that fits more with the image that I wanted
***For context: The video hurts my soul. The software in QGIS wouldn't let me export the video it created, so I downloaded like 145 something screenshots, put them in order, and made a video with some random app on my computer. It's gross, and I'm not too fond of it. It also doesn't show multiple dots at once, which defeats the purpose.***
- [ ] Edit the Analysis Page
***There are grammar/spelling errors, and I wouldn't say I like how I compared the two media.***
- [ ] Add a sound to the website or a part of it
***Music makes things better. Also, Cyborg screaming BOOYAH seems like instant serotonin that I owe myself to try to make happen.***
- [ ] Revise Methodology 
***ahhhhhhhhh. That's all.***
- [ ] Revise our blurbs
@smdunn921 @amberpeddicord 
- [x] Free space
***I have run out of things to add to this list. Also, it's fair to have a free space, so I can have one item checked off on the list at all times.***

### ***I'M DONE. HAVE A NICE DAY. BYE.***

_Beast Boy_ out.
